[server]
headless = true
address = "127.0.0.1"
port = 5000
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#4B56D2"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#F8F9FA"
font = "sans serif"
